---
- name: "main.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
  - name: Skel block
    block:
        - name: Create vim configuration file
          copy:
            src: /root/.bashrc
            dest: /etc/skel/.bashrc
            remote_src: true

        - name: Colorize shell prompt
          lineinfile:
            path: /etc/skel/.bashrc
            line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
            state: present

        - name: Alias vi to vim
          lineinfile:
            path: /etc/skel/.bashrc
            line: "alias vi='vim'"
            state: present

        - name: Create vim configuration file
          file:
            path: /etc/skel/.vimrc
            state: touch
            owner: root
            group: root
            mode: 0644

        - name: Configure vim
          blockinfile:
            path: /etc/skel/.vimrc
            block: |
              set nocompatible
              set number
              set autoindent
              syntax on
              highlight Comment ctermfg=LightCyan
            marker: ""
            state: present
  
  - name: Root block
    block:
      - name: Colorize root shell prompt
        lineinfile:
          path: /root/.bashrc
          line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
          state: present

      - name: Alias vi to vim
        lineinfile:
          path: /root/.bashrc
          line: "alias vi='vim'"
          state: present

      - name: Create vim configuration file
        file:
          path: /root/.vimrc
          state: touch
          owner: root
          group: root
          mode: 0644

      - name: Configure vim
        blockinfile:
          path: /root/.vimrc
          block: |
            set nocompatible
            set number
            set autoindent
            syntax on
            highlight Comment ctermfg=LightCyan
          marker: ""
          state: present

  - name: Disable GSSAPIAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
      state: present

  - name: Update CA bundle
    get_url:
      url: https://curl.haxx.se/ca/cacert.pem
      dest: /etc/pki/tls/certs/ca-bundle.crt
      force: yes

  - name: Install epel repo 
    dnf:
      name: "oracle-epel-release-el8"
      state: latest

  - name: Upgrade all packages 
    dnf:
      name: "*"
      state: latest

  - name: Install packages
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - htop
      - wget

  - name: Install open-vm-tools
    yum:
      name: open-vm-tools
      state: latest